#!/g/g19/atsusr/nightlyTests/local/bin/python
import sys

try:
    import ats
except ImportError:
    print >>sys.stderr, "ats module cannot be imported; check Python path."
    print >>sys.stderr, sys.path
    raise SystemExit, 1

result = ats.manager.main()
sys.exit(result)

